### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by TheFurnace** [passport/express-4.x-facebook-example#12]
PS C:\Users\ferda\dev\web\express-4.x-facebook-example> node server.js
C:\Users\ferda\dev\web\express-4.x-facebook-example\node_modules\passport-oauth2\lib\strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\ferda\dev\web\express-4.x-facebook-example\node_modules\passport-oauth2\lib\str
ategy.js:82:34)
    at new Strategy (C:\Users\ferda\dev\web\express-4.x-facebook-example\node_modules\passport-facebook\lib\strategy.js:
54:18)
    at Object.<anonymous> (C:\Users\ferda\dev\web\express-4.x-facebook-example\server.js:13:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

**Comment by neihcnim** [comment]
I too hit this error. You are suppose to have a clientID or appID option.

Go to developer.facebook.com, click on 'my app', settings, basic to get your clientID (or appid) and app secret. 

Modify, clientID and clientSecret with your appid and app secret in server.js .

**Comment by joeykay9** [comment]
> I too hit this error. You are suppose to have a clientID or appID option.
> 
> Go to developer.facebook.com, click on 'my app', settings, basic to get your clientID (or appid) and app secret.
> 
> Modify, clientID and clientSecret with your appid and app secret in server.js line 14.

Did that but still getting the same error

**Comment by rithiksachdev** [comment]
@joeykay9 did you find any solution?

**Comment by rithiksachdev** [comment]
@jaredhanson the problem still persists, can you please suggest a solution?
